# Site settings
title: First Jekyll Practice
email: mundert@gmail.com
description: > 
  First time using Jekyll to generate a static site.
baseurl: "/startjekyll" # the subpath of your site, e.g. /blog/
url: "http://tmund.github.io" # the base hostname & protocol for your site
twitter_username: teemund
github_username:  tmund

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
